### ISSUE TITLE
Notification on feedback

### ISSUE THREAD

**Issue by ksuess** [RegioneER/rer.customersatisfaction#11]
Would it make sense to let an event be fired on new feedback, or is there already a possibility to notify a moderator on new feedback?

I am using this via REST API/it's corresponding Volto add-on.

**Comment by cekk** [comment]
Yes, it could be a great idea firing and event on feedback!

Do you have time to make a pr about that?

**Comment by ksuess** [comment]
> Yes, it could be a great idea firing and event on feedback!
> 
> Do you have time to make a pr about that?

Yes. Do you prefer a fork or branch?

**Comment by tassoman** [comment]
Thanks @ksuess for your tidy contribution, I asked @cekk a technical review

**Comment by ksuess** [comment]
Would you mind reviewing, @cekk.
