### ISSUE TITLE
honeypot o recaptcha?

### ISSUE THREAD

**Issue by tassoman** [RegioneER/rer.customersatisfaction#14]
[Questa immagine ](https://github.com/RegioneER/rer.customersatisfaction/raw/main/docs/customer-satisfaction_1-Recensione.jpg)è ancora valida? Altrimenti occorre aggiornare il README.

Si usa honeypot oppure recaptcha? Si usano entrambi, se configurati?

**Comment by cekk** [comment]
Honeypot..hai ragione, ho aggiornato lo screenshot
