### ISSUE TITLE
errore installazione add-on su plone 5.2.1

### ISSUE THREAD

**Issue by fsacchi74** [RegioneER/rer.customersatisfaction#6]
Abbiamo provato ad installare l'add-on su un Plone 5.2.1
Il build non restituiesce errori, ma quando startiamo 
l'istanza di plone, va in loop con questo errore:

2022-10-26 14:41:46,609 INFO    [redturtle.tiles.management:42][MainThread] [PATCH] Applied get_relateditems_options patch
2022-10-26 14:41:55,952 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2022-10-26 14:41:55,959 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2022-10-26 14:41:56,345 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied sql_quote patch
2022-10-26 14:41:56,487 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied in_portal patch
2022-10-26 14:41:56,487 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied password_validation patch
2022-10-26 14:41:56,502 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied pac patch
2022-10-26 14:41:56,528 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied content patch
2022-10-26 14:41:56,533 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied layout patch
2022-10-26 14:41:56,631 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied restapi_local_roles patch
2022-10-26 14:41:56,632 INFO    [Products.PloneHotfix20200121:57][MainThread] Hotfix installed
2022-10-26 14:42:11,965 WARNING [TemporaryStorage:93][MainThread] DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

2022-10-26 14:42:12,290 INFO    [redturtle.tiles.management:42][MainThread] [PATCH] Applied get_relateditems_options patch

Può essere un conflitto con altri add-on o versioni ?
Grazie
Federica

**Comment by cekk** [comment]
Scusa, ma io non vedo errori nel traceback che hai messo.
Vedo dei warning, ma non danno problemi al funzionamento del sito.

**Comment by fsacchi74** [comment]
non segnala un errore, ma va in loop 
e scrive sempre questo pezzo di log e 
plone non riparte 

 Grazie

**Comment by fsacchi74** [comment]
Eccolo:

[buildout]

# buildout.sanitycheck makes sure you're not running buildout
# as root.
extensions =
    buildout.sanitycheck

############################################
# Plone Component Versions
# ------------------------
# This version of the Unified Installer has the components of Plone 5
# preloaded so that it can install without an Internet connection.
# If you want to update, uncomment the "http://..." line below,
# edit it to point to the current version URL, comment out the
# "versions.cfg" line and run "bin/buildout" while attached to the
# Internet. Generally, you only want to do that as part of a planned migration.
# Note that if you are updating components, you should also check the versions
# section at the end of this file, since recipes or components other than
# those of Zope and Plone may need updating at the same time.
#
extends =
    base.cfg
    release-5.2.1-versions.cfg
#    http://dist.plone.org/release/5.2.1/versions.cfg

# If you change your Plone version, you'll also need to update
# the repository link below.
find-links +=
    http://dist.plone.org/release/5.2.1

# This user will own the non-data parts of the installation, and should be used to
# run buildout.
buildout-user = plone_buildout
# A flag to tell the Unified Installer whether or not to document sudo use.
need-sudo = yes


############################################
# Eggs
# ----
# Add an indented line to the eggs section for any Python
# eggs or packages you wish to include in your Plone instance.
#
# Note that versions may be specified here or in the [versions]
# section below. You should always specify versions that you know
# are compatible with the Plone release and at an acceptable
# development level.
#
# If you update to a later version of Plone, remove the hotfix.
#
eggs =
    Plone
    Pillow
    design.plone.theme
    collective.behavior.seo
    rer.cookieconsent
    plone.app.imaging
    redturtle.gallery
    sitemap42
    redturtle.patterns.slider
    collective.behavior.banner
    Products.PloneHotfix20200121
    Products.PloneHotfix20210518
    redturtle.tiles.management
    rer.customersatisfaction[collective_recaptcha]
############################################
# ZCML Slugs
# ----------
# Some eggs need ZCML slugs to tell Zope to
# use them. This is increasingly rare.
zcml =
#    plone.reload


############################################
# Development Eggs
# ----------------
# You can use paster to create "development eggs" to
# develop new products/themes. Put these in the src/
# directory.
# You will also need to add the egg names in the
# eggs section above, and may also need to add them
# to the zcml section.
#
# Provide the *paths* to the eggs you are developing here:
develop =
#    src/my.package


############################################
# var Directory
# -------------
# Sets the target directory for the "var" components of the install such as
# database and log files.
#
var-dir=${buildout:directory}/var


############################################
# Backup Directory
# ----------------
# Sets the target directory for the bin/backup and bin/snapshotbackup
# commands. Default is inside this project's var directory, but ideally
# this should be on a separate volume or backup server.
#
backups-dir=${buildout:var-dir}


############################################
# Initial User
# ------------
# This is the user id and password that will be used to create the initial
# user id that will allow you to log in and create a Plone site. This only
# sets the initial password; it will not allow you to change an already
# existing password. If you change the admin password via the web interface,
# the one below will no longer be valid.
# If you find yourself locked out of your Zope/Python installation, you may
# add an emergency user via "bin/plonectl adduser".
user=admin:password


############################################
# Debug Options
# -------------
# Start Zope/Plone instances in "fg" mode to turn on debug mode;
# this will dramatically slow Plone.
#
# Add-on developers should turn deprecation warnings on
deprecation-warnings = off
# change verbose-security to "on" for useful security errors while developing
verbose-security = off


############################################
# Parts Specification
#--------------------
# Specifies the components that should be included in the buildout.
# Most are defined in the base.cfg extension; you may add your
# own if you need them at the end of this file.
parts =
    instance
    repozo
    backup
    zopepy
    unifiedinstaller
    precompiler
    setpermissions

############################################
# Major Parts
# ----------------------
# These common parts make use of sane base settings from
# base.cfg. To customize a part, just add whatever options
# you need. Read base.cfg for common settings.

[instance]
<= instance_base
recipe = plone.recipe.zope2instance
http-address = 8080



############################################
# Versions Specification
# ----------------------
# Version information supplied here will "pin" Python packages to a particular
# version number, even when you use the "newest" flag running buildout.
# Specifying versions for all packages is a good idea and can prevent
# accidental changes when you add new packages to your buildout.
# Note that versions specified here will override those specified earlier
# in the configuration, including those from the Plone and Zope version
# config files.
#
[versions]

buildout.sanitycheck = 1.0.2
collective.recipe.backup = 4.1.0
plone.recipe.unifiedinstaller = 5.2b1
Products.PloneHotfix20200121 = 1.1
redturtle.tiles.management = 3.0.0

**Comment by fsacchi74** [comment]
abbiamo provato ad eliminare qualche altro add-on, ma senza successo

**Comment by tassoman** [comment]
Ciao @fsacchi74 ti consiglio di ripetere la build, nel caso ci fossero ancora problemi, disabilita questo plugin e ripeti la build.  
Nel caso in cui la seconda build dovesse funzionare, allora potrebbe esserci qualche ipotetico malfunzionamento da indagare. Nel caso, ti chiederei di aprire una nuova issue, indicando informazioni su come riprodurre la build ed ottenere un adeguato log di debug.
